name: Chat Service Frontend PR Build

on:
  pull_request:
    paths:
      - "apps/frontend/hushchat-mobile/**"

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

jobs:
  lint-and-prettier-check:
    name: Lint & Prettier Check
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Node.js + Install dependencies
        uses: ./.github/actions/setup-node-yarn-install

      - name: Run ESLint check
        run: yarn lint:check

      - name: Run Prettier check
        run: yarn prettier:check

  build-android:
    name: Build Android
    runs-on: ubuntu-latest
    needs: lint-and-prettier-check

    defaults:
      run:
        working-directory: apps/frontend/hushchat-mobile

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Get changed files
        id: changed-files
        uses: tj-actions/changed-files@v41
        with:
          files: |
            apps/frontend/hushchat-mobile/metro.config.js
            apps/frontend/hushchat-mobile/package.json
            apps/frontend/hushchat-mobile/app.config.ts
            apps/frontend/hushchat-mobile/yarn.lock
            apps/frontend/hushchat-mobile/android/**

      - name: Set up Node.js + Install dependencies
        if: steps.changed-files.outputs.any_changed == 'true'
        uses: ./.github/actions/setup-node-yarn-install

      - name: Set up JDK for Android
        if: steps.changed-files.outputs.any_changed == 'true'
        uses: actions/setup-java@v3
        with:
          distribution: 'adopt'
          java-version: '21'

      - name: Set up Android SDK
        if: steps.changed-files.outputs.any_changed == 'true'
        uses: android-actions/setup-android@v3

      - name: Install Expo and EAS CLIs
        if: steps.changed-files.outputs.any_changed == 'true'
        run: yarn add -W expo-cli eas-cli

      - name: Build Android
        if: steps.changed-files.outputs.any_changed == 'true'
        run: yarn build-android