name: Chat Service Backend Main Build

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

on:
  push:
    branches:
      - main
    paths:
      - 'apps/backend/chat-service/**'

jobs:
  build-chat-service:
    name: Build Chat Service
    runs-on: ubuntu-latest

    env:
      # AWS / S3
      TEST_CLOUD_AWS_ACCESS_KEY: ${{ secrets.DEV_CLOUD_AWS_ACCESS_KEY }}
      TEST_CLOUD_AWS_SECRET_KEY: ${{ secrets.DEV_CLOUD_AWS_SECRET_KEY }}
      TEST_PRIVATE_BUCKET_NAME: ${{ vars.DEV_PRIVATE_BUCKET_NAME }}

      # Logging / ELK
      TEST_LOG_ELK_HOST: ${{ vars.DEV_LOG_ELK_HOST }}
      TEST_LOG_ELK_PORT: ${{ vars.DEV_LOG_ELK_PORT }}

      # Health Checks
      TEST_HEALTH_CHECK_REDIS_SECRET_KEY: ${{ secrets.DEV_HEALTH_CHECK_REDIS_SECRET_KEY }}
      TEST_HEALTH_CHECK_COMMIT_INFO_SECRET_KEY: ${{ secrets.DEV_HEALTH_CHECK_COMMIT_INFO_SECRET_KEY }}

      # AWS Cognito
      TEST_AWS_COGNITO_USER_POOL_ID: ${{ vars.DEV_AWS_COGNITO_USER_POOL_ID }}
      TEST_AWS_COGNITO_REGION: ${{ vars.DEV_AWS_COGNITO_REGION }}
      TEST_AWS_COGNITO_JWKS_URL: ${{ vars.DEV_AWS_COGNITO_JWKS_URL }}
      TEST_AWS_COGNITO_CLIENT_ID: ${{ secrets.DEV_AWS_COGNITO_CLIENT_ID }}

      # Chat unit test users
      TEST_CHAT_ADMIN_EMAIL: ${{ vars.DEV_CHAT_ADMIN_EMAIL }}
      TEST_CHAT_ADMIN_PASSWORD: ${{ vars.DEV_CHAT_ADMIN_PASSWORD }}
      TEST_CHAT_PARTICIPANT_EMAIL: ${{ vars.DEV_CHAT_PARTICIPANT_EMAIL }}
      TEST_CHAT_PARTICIPANT_PASSWORD: ${{ vars.DEV_CHAT_PARTICIPANT_PASSWORD }}

    steps:
      - name: Clone repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 1

      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'

      - name: Set up Node.js + Install dependencies
        uses: ./.github/actions/setup-node-yarn-install

      - name: Build chat service
        run: |
          mvn -f apps/backend/chat-service/pom.xml clean install
          mvn -f apps/backend/chat-service/pom.xml jacoco:report
