name: Chat Service Backend PR Build

on:
  pull_request:
    paths:
      - "apps/backend/chat-service/**"

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

jobs:
  build-chat-service:
    name: Build
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 1

      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          java-version: "21"
          distribution: "temurin"
          cache: 'maven'

      - name: Set up Node.js + Install dependencies
        uses: ./.github/actions/setup-node-yarn-install

      - name: Compile the chat service
        if: ${{ github.event.pull_request.head.repo.full_name != github.repository }}
        run: mvn -f apps/backend/chat-service/pom.xml clean compile -DskipTests

      - name: Compile and test the chat service
        if: ${{ github.event.pull_request.head.repo.full_name == github.repository }}
        run: mvn -f apps/backend/chat-service/pom.xml clean compile